name: Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: deploy

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: ${{ vars.EVENT_TYPE }}
          repository: ${{ vars.REPO_URL }}
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "${{ github.repository }}"}'
